# Generated by Django 5.1.7 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
